### PR TITLE
Update review page

### PR DESCRIPTION
**Pull request by calvinlu3**
This fixes https://github.com/oncokb/oncokb-pipeline/issues/402

We will use this branch to make all the updates the review page

## Changes
New /review route for Review Page
Optimisic UI render upon accept/reject
Remove gene and meta listener

### CODE REVIEW

**Comment by calvinlu3** [comment]
@zhx828 All branches have been merged into this feature branch. This PR is ready for a review. Thanks!

**Comment by zhx828** [comment]
We don't have to fix in this round. but this is a weird interface. 
Screenshot 2024-06-19 at 10 18 09 AM

**Review by zhx828 — APPROVED** [review]
Why the test is failing? We also need to merge the latest rc. The package-lock.json is gone now.

**Comment by calvinlu3** [comment]
> We don't have to fix in this round. but this is a weird interface. Screenshot 2024-06-19 at 10 18 09 AM

Agreed. Will create a follow-up discussion ticket.



> Why the test is failing? We also need to merge the latest rc. The package-lock.json is gone now.

I increased the left padding a bit for collapsibles. Also, rebased.

**Pull request merged**
